// Location presets for geo targeting

export interface LocationPreset {
  id: string;
  name: string;
  country: string;
  region: string;
  city: string;
  zip: string;
  metro: string;
  lat: number;
  lon: number;
  utcoffset: number;
}

export const LOCATION_PRESETS: LocationPreset[] = [
  {
    id: 'sf',
    name: 'San Francisco, CA',
    country: 'USA',
    region: 'CA',
    city: 'San Francisco',
    zip: '94102',
    metro: '807',
    lat: 37.7749,
    lon: -122.4194,
    utcoffset: -480,
  },
  {
    id: 'nyc',
    name: 'New York, NY',
    country: 'USA',
    region: 'NY',
    city: 'New York',
    zip: '10001',
    metro: '501',
    lat: 40.7128,
    lon: -74.006,
    utcoffset: -300,
  },
  {
    id: 'la',
    name: 'Los Angeles, CA',
    country: 'USA',
    region: 'CA',
    city: 'Los Angeles',
    zip: '90001',
    metro: '803',
    lat: 34.0522,
    lon: -118.2437,
    utcoffset: -480,
  },
  {
    id: 'chicago',
    name: 'Chicago, IL',
    country: 'USA',
    region: 'IL',
    city: 'Chicago',
    zip: '60601',
    metro: '602',
    lat: 41.8781,
    lon: -87.6298,
    utcoffset: -360,
  },
  {
    id: 'houston',
    name: 'Houston, TX',
    country: 'USA',
    region: 'TX',
    city: 'Houston',
    zip: '77001',
    metro: '618',
    lat: 29.7604,
    lon: -95.3698,
    utcoffset: -360,
  },
  {
    id: 'miami',
    name: 'Miami, FL',
    country: 'USA',
    region: 'FL',
    city: 'Miami',
    zip: '33101',
    metro: '528',
    lat: 25.7617,
    lon: -80.1918,
    utcoffset: -300,
  },
  {
    id: 'seattle',
    name: 'Seattle, WA',
    country: 'USA',
    region: 'WA',
    city: 'Seattle',
    zip: '98101',
    metro: '819',
    lat: 47.6062,
    lon: -122.3321,
    utcoffset: -480,
  },
  {
    id: 'boston',
    name: 'Boston, MA',
    country: 'USA',
    region: 'MA',
    city: 'Boston',
    zip: '02101',
    metro: '506',
    lat: 42.3601,
    lon: -71.0589,
    utcoffset: -300,
  },
  {
    id: 'denver',
    name: 'Denver, CO',
    country: 'USA',
    region: 'CO',
    city: 'Denver',
    zip: '80201',
    metro: '751',
    lat: 39.7392,
    lon: -104.9903,
    utcoffset: -420,
  },
  {
    id: 'atlanta',
    name: 'Atlanta, GA',
    country: 'USA',
    region: 'GA',
    city: 'Atlanta',
    zip: '30301',
    metro: '524',
    lat: 33.749,
    lon: -84.388,
    utcoffset: -300,
  },
  {
    id: 'london',
    name: 'London, UK',
    country: 'GBR',
    region: '',
    city: 'London',
    zip: 'SW1A 1AA',
    metro: '',
    lat: 51.5074,
    lon: -0.1278,
    utcoffset: 0,
  },
  {
    id: 'paris',
    name: 'Paris, France',
    country: 'FRA',
    region: '',
    city: 'Paris',
    zip: '75001',
    metro: '',
    lat: 48.8566,
    lon: 2.3522,
    utcoffset: 60,
  },
  {
    id: 'berlin',
    name: 'Berlin, Germany',
    country: 'DEU',
    region: '',
    city: 'Berlin',
    zip: '10115',
    metro: '',
    lat: 52.52,
    lon: 13.405,
    utcoffset: 60,
  },
  {
    id: 'tokyo',
    name: 'Tokyo, Japan',
    country: 'JPN',
    region: '',
    city: 'Tokyo',
    zip: '100-0001',
    metro: '',
    lat: 35.6762,
    lon: 139.6503,
    utcoffset: 540,
  },
  {
    id: 'sydney',
    name: 'Sydney, Australia',
    country: 'AUS',
    region: 'NSW',
    city: 'Sydney',
    zip: '2000',
    metro: '',
    lat: -33.8688,
    lon: 151.2093,
    utcoffset: 660,
  },
  {
    id: 'toronto',
    name: 'Toronto, Canada',
    country: 'CAN',
    region: 'ON',
    city: 'Toronto',
    zip: 'M5H 2N2',
    metro: '',
    lat: 43.6532,
    lon: -79.3832,
    utcoffset: -300,
  },
  {
    id: 'mumbai',
    name: 'Mumbai, India',
    country: 'IND',
    region: 'MH',
    city: 'Mumbai',
    zip: '400001',
    metro: '',
    lat: 19.076,
    lon: 72.8777,
    utcoffset: 330,
  },
  {
    id: 'saopaulo',
    name: 'São Paulo, Brazil',
    country: 'BRA',
    region: 'SP',
    city: 'São Paulo',
    zip: '01310-100',
    metro: '',
    lat: -23.5505,
    lon: -46.6333,
    utcoffset: -180,
  },
];

export const getLocationById = (id: string): LocationPreset | undefined => {
  return LOCATION_PRESETS.find(loc => loc.id === id);
};

export const getLocationsByCountry = (country: string): LocationPreset[] => {
  return LOCATION_PRESETS.filter(loc => loc.country === country);
};
