// Preset templates for common bid request configurations

import type { BidRequestFormState } from '../types/formState';

export interface Preset {
  id: string;
  name: string;
  description: string;
  category: 'desktop' | 'mobile' | 'ctv' | 'tablet';
  icon: string;
  state: Partial<BidRequestFormState>;
}

const DEFAULT_DESKTOP_DEVICE = {
  ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  devicetype: 2,
  make: '',
  model: '',
  os: 'Windows',
  osv: '10',
  w: 1920,
  h: 1080,
  pxratio: 1.0,
  js: true,
  language: 'en',
  connectiontype: 1,
};

const DEFAULT_MOBILE_DEVICE = {
  ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
  devicetype: 4,
  make: 'Apple',
  model: 'iPhone',
  os: 'iOS',
  osv: '17.0',
  w: 390,
  h: 844,
  pxratio: 3.0,
  js: true,
  language: 'en',
  connectiontype: 6,
};

const DEFAULT_ANDROID_DEVICE = {
  ua: 'Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36',
  devicetype: 4,
  make: 'Google',
  model: 'Pixel 8 Pro',
  os: 'Android',
  osv: '14',
  w: 412,
  h: 915,
  pxratio: 2.625,
  js: true,
  language: 'en',
  connectiontype: 6,
};

const DEFAULT_CTV_DEVICE = {
  ua: 'Mozilla/5.0 (SMART-TV; LINUX; Tizen 7.0) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.0 Chrome/85.0.4183.93 Safari/537.36',
  devicetype: 3,
  make: 'Samsung',
  model: 'Smart TV',
  os: 'Tizen',
  osv: '7.0',
  w: 1920,
  h: 1080,
  pxratio: 1.0,
  js: true,
  language: 'en',
  connectiontype: 1,
};

const DEFAULT_TABLET_DEVICE = {
  ua: 'Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
  devicetype: 5,
  make: 'Apple',
  model: 'iPad',
  os: 'iOS',
  osv: '17.0',
  w: 1024,
  h: 1366,
  pxratio: 2.0,
  js: true,
  language: 'en',
  connectiontype: 2,
};

const DEFAULT_US_GEO = {
  country: 'USA',
  region: 'CA',
  city: 'San Francisco',
  zip: '94102',
  lat: 37.7749,
  lon: -122.4194,
  type: 2,
  utcoffset: -480,
};

const DEFAULT_BANNER_SETTINGS = {
  pos: 1,
  api: [5, 6, 7],
  mimes: ['image/jpeg', 'image/png', 'image/gif', 'text/html', 'application/javascript'],
  battr: [],
  btype: [],
};

const DEFAULT_VIDEO_SETTINGS = {
  mimes: ['video/mp4', 'video/webm'],
  minduration: 0,
  maxduration: 30,
  protocols: [2, 3, 5, 6],
  w: 640,
  h: 360,
  startdelay: 0,
  plcmt: 1,
  linearity: 1,
  skip: false,
  skipmin: 0,
  skipafter: 0,
  playbackmethod: [2],
  delivery: [1, 2],
  pos: 0,
  api: [],
  battr: [],
  minbitrate: null,
  maxbitrate: null,
  boxingallowed: true,
  playbackend: 1,
};

export const PRESETS: Preset[] = [
  {
    id: 'desktop-leaderboard',
    name: 'Desktop Leaderboard',
    description: 'Standard 728x90 leaderboard for desktop browsers',
    category: 'desktop',
    icon: '🖥️',
    state: {
      device: {
        ...DEFAULT_DESKTOP_DEVICE,
        ip: '73.158.64.100',
        ipv6: '',
        hwv: '',
        ppi: 96,
        dnt: false,
        lmt: false,
        carrier: '',
        mccmnc: '',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 728,
          h: 90,
          format: [{ w: 728, h: 90 }, { w: 970, h: 90 }],
          ...DEFAULT_BANNER_SETTINGS,
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 0.5,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'desktop-medium-rectangle',
    name: 'Desktop Medium Rectangle',
    description: 'Standard 300x250 medium rectangle for desktop',
    category: 'desktop',
    icon: '🖥️',
    state: {
      device: {
        ...DEFAULT_DESKTOP_DEVICE,
        ip: '73.158.64.100',
        ipv6: '',
        hwv: '',
        ppi: 96,
        dnt: false,
        lmt: false,
        carrier: '',
        mccmnc: '',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 300,
          h: 250,
          format: [{ w: 300, h: 250 }, { w: 336, h: 280 }],
          ...DEFAULT_BANNER_SETTINGS,
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 0.75,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'mobile-banner',
    name: 'Mobile Banner',
    description: '320x50 mobile banner for iOS Safari',
    category: 'mobile',
    icon: '📱',
    state: {
      device: {
        ...DEFAULT_MOBILE_DEVICE,
        ip: '174.194.72.15',
        ipv6: '',
        hwv: '',
        ppi: 460,
        dnt: false,
        lmt: false,
        carrier: 'AT&T',
        mccmnc: '310-410',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 320,
          h: 50,
          format: [{ w: 320, h: 50 }, { w: 320, h: 100 }],
          ...DEFAULT_BANNER_SETTINGS,
          api: [3, 5, 6, 7],
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 0.35,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'mobile-interstitial',
    name: 'Mobile Interstitial',
    description: 'Full-screen interstitial for mobile apps',
    category: 'mobile',
    icon: '📱',
    state: {
      device: {
        ...DEFAULT_MOBILE_DEVICE,
        ip: '174.194.72.15',
        ipv6: '',
        hwv: '',
        ppi: 460,
        dnt: false,
        lmt: false,
        carrier: 'Verizon',
        mccmnc: '311-480',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 320,
          h: 480,
          format: [{ w: 320, h: 480 }],
          pos: 7,
          api: [3, 5, 6, 7],
          mimes: ['image/jpeg', 'image/png', 'text/html', 'application/javascript'],
          battr: [],
          btype: [],
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 2.0,
        bidfloorcur: 'USD',
        secure: true,
        instl: true,
        tagid: '',
      }],
    },
  },
  {
    id: 'android-banner',
    name: 'Android Banner',
    description: '320x50 mobile banner for Android Chrome',
    category: 'mobile',
    icon: '🤖',
    state: {
      device: {
        ...DEFAULT_ANDROID_DEVICE,
        ip: '108.45.92.200',
        ipv6: '',
        hwv: '',
        ppi: 420,
        dnt: false,
        lmt: false,
        carrier: 'T-Mobile',
        mccmnc: '310-260',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 320,
          h: 50,
          format: [{ w: 320, h: 50 }, { w: 320, h: 100 }],
          ...DEFAULT_BANNER_SETTINGS,
          api: [3, 5, 6, 7],
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 0.30,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'ctv-banner',
    name: 'Connected TV',
    description: 'Large format banner for Connected TV',
    category: 'ctv',
    icon: '📺',
    state: {
      device: {
        ...DEFAULT_CTV_DEVICE,
        ip: '76.102.81.22',
        ipv6: '',
        hwv: '',
        ppi: 40,
        dnt: false,
        lmt: false,
        carrier: '',
        mccmnc: '',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 970,
          h: 250,
          format: [{ w: 970, h: 250 }],
          pos: 7,
          api: [7],
          mimes: ['image/jpeg', 'image/png', 'text/html'],
          battr: [],
          btype: [],
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 5.0,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'tablet-medium-rectangle',
    name: 'Tablet Medium Rectangle',
    description: '300x250 for iPad Safari',
    category: 'tablet',
    icon: '📲',
    state: {
      device: {
        ...DEFAULT_TABLET_DEVICE,
        ip: '68.194.89.155',
        ipv6: '',
        hwv: '',
        ppi: 264,
        dnt: false,
        lmt: false,
        carrier: '',
        mccmnc: '',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [{
        id: '1',
        mediaType: 'banner' as const,
        banner: {
          w: 300,
          h: 250,
          format: [{ w: 300, h: 250 }, { w: 336, h: 280 }],
          ...DEFAULT_BANNER_SETTINGS,
          api: [3, 5, 6, 7],
        },
        video: DEFAULT_VIDEO_SETTINGS,
        bidfloor: 0.60,
        bidfloorcur: 'USD',
        secure: true,
        instl: false,
        tagid: '',
      }],
    },
  },
  {
    id: 'multi-impression',
    name: 'Multi-Impression',
    description: 'Multiple banner sizes in one request',
    category: 'desktop',
    icon: '📊',
    state: {
      device: {
        ...DEFAULT_DESKTOP_DEVICE,
        ip: '73.158.64.100',
        ipv6: '',
        hwv: '',
        ppi: 96,
        dnt: false,
        lmt: false,
        carrier: '',
        mccmnc: '',
        ifa: '',
      },
      geo: { ...DEFAULT_US_GEO, accuracy: null, metro: '' },
      impressions: [
        {
          id: '1',
          mediaType: 'banner' as const,
          banner: {
            w: 728,
            h: 90,
            format: [{ w: 728, h: 90 }],
            pos: 4,
            api: [5, 6, 7],
            mimes: ['image/jpeg', 'image/png', 'text/html'],
            battr: [],
            btype: [],
          },
          video: DEFAULT_VIDEO_SETTINGS,
          bidfloor: 0.5,
          bidfloorcur: 'USD',
          secure: true,
          instl: false,
          tagid: 'header-ad',
        },
        {
          id: '2',
          mediaType: 'banner' as const,
          banner: {
            w: 300,
            h: 250,
            format: [{ w: 300, h: 250 }],
            pos: 6,
            api: [5, 6, 7],
            mimes: ['image/jpeg', 'image/png', 'text/html'],
            battr: [],
            btype: [],
          },
          video: DEFAULT_VIDEO_SETTINGS,
          bidfloor: 0.75,
          bidfloorcur: 'USD',
          secure: true,
          instl: false,
          tagid: 'sidebar-ad',
        },
        {
          id: '3',
          mediaType: 'banner' as const,
          banner: {
            w: 300,
            h: 600,
            format: [{ w: 300, h: 600 }, { w: 160, h: 600 }],
            pos: 6,
            api: [5, 6, 7],
            mimes: ['image/jpeg', 'image/png', 'text/html'],
            battr: [],
            btype: [],
          },
          video: DEFAULT_VIDEO_SETTINGS,
          bidfloor: 1.0,
          bidfloorcur: 'USD',
          secure: true,
          instl: false,
          tagid: 'sidebar-tall',
        },
      ],
    },
  },
];

export const getPresetById = (id: string): Preset | undefined => {
  return PRESETS.find(p => p.id === id);
};

export const getPresetsByCategory = (category: Preset['category']): Preset[] => {
  return PRESETS.filter(p => p.category === category);
};
